---
apiVersion: v1
kind: Namespace
metadata:
  name: sms-devops-gateway

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sms-devops-gateway-configmap
  namespace: sms-devops-gateway
data:
  config.json: |
    {
      "receiver": [
        {
          "name": "alert-devops",
          "mobile": "sdt-devops-1, sdt-devops-2"
        },
        {
          "name": "alert-vh",
          "mobile": "sdt-devops-1, sdt-devops-2"
        }
      ],
      "default_receiver": {
        "mobile": "sdt"
      }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sms-devops-gateway-ignore-alert-configmap
  namespace: sms-devops-gateway
data:
  ignore-alert.json: |
    {
      "ignore": [
        {
          "cluster": "d1_coreup",
          "namespaces": [
            {
              "name": "infra-monitoring",
              "pods": ["abc", "def"]
            },
            {
              "name": "dev-tools",
              "pods": []
            }
          ]
        },
        {
          "cluster": "d2_test",
          "namespaces": [
            {
              "name": "test-namespace",
              "pods": ["ghi"]
            }
          ]
        }
      ]
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: sms-devops-gatewaysecret
  namespace: sms-gateway
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <encode_data>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-gateway
  namespace: sms-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sms-gateway
  template:
    metadata:
      labels:
        app: sms-gateway
    spec:
      containers:
        - name: sms-gateway
          image: your-dockerhub-username/sms-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /config.json
              subPath: config.json
            - name: ignore-alert-volume
              mountPath: /ignore-alert.json
              subPath: ignore-alert.json

      volumes:
        - name: config-volume
          configMap:
            name: sms-devops-gateway-configmap
        - name: ignore-alert-volume
          configMap:
            name: sms-devops-gateway-ignore-alert
      imagePullSecrets:
        - name: sms-devops-gateway-secret

---
apiVersion: v1
kind: Service
metadata:
  name: sms-gateway
  namespace: sms-gateway
spec:
  selector:
    app: sms-gateway
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sms-gateway
  namespace: sms-gateway
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /sms
spec:
  rules:
    - host: sms-gateway.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sms-gateway
                port:
                  number: 8080
